"$schema" = 'https://starship.rs/config-schema.json'

[character]
error_symbol = "λ"
success_symbol = "λ"

[aws]
symbol = "  "

[conda]
symbol = "  "

[git_branch]
symbol = "  "

[golang]
symbol = "  "

[hg_branch]
symbol = "  "

[java]
symbol = "  "

[memory_usage]
disabled = true
symbol = "  "

[nodejs]
symbol = "  "

[package]
symbol = "  "

[php]
symbol = "  "

[python]
symbol = "  "

[ruby]
symbol = "  "

[rust]
symbol = "  "
