[settings]
idiomatic_version_file_enable_tools = ["ruby", "terraform"]

[settings.ruby]
compile = false

[settings.python]
compile = false

[tools]
direnv = "latest"
node = "24"
"github:mizchi/actrun" = "latest"
"github:suzuki-shunsuke/pinact" = "latest"
"dprint" = "latest"
"github:rhysd/actionlint" = "latest"
"github:zizmorcore/zizmor" = "latest"
"shfmt" = "3.13.1"
